services:
  - type: web
    name: dodge-game
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
      - path: /*
        name: Content-Type
        value: text/html; charset=utf-8
    routes:
      - type: rewrite
        source: /*
        destination: /game.html

